# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
TiposUsuario.create([{ tipo: 'Admin' }, { tipo: 'Empleado A' }, { tipo: 'Empleado B' }, { tipo: 'Cliente' }])

EstadosOrdene.create([{ estado: 'Pendiente' }, { estado: 'En proceso' }, { estado: 'Listo' }, { estado: 'Rechazado' },
                      { estado: 'Aceptado' }])
Producto.create([{ nombre: 'Lona 13 onzas alta resolución', descripcion: 'De 1 a 3/4 M2 se cobra metro completo (1m2 a .76)',
                   precioPublico: '98', precioMaquila:'65' },
                 { nombre: 'Lona 13 onzas alta resolución', descripcion: 'Menos de 3/4 hasta 1/2 M2 el costo es el 40% extra (.75 a .51)',
                   precioPublico: '137', precioMaquila:'91' },
                 { nombre: 'Lona 13 onzas alta resolución', descripcion: 'Menos de 1/2 hasta 1/4 M2 el costo es 60% extra (.50 a .25)',
                   precioPublico: '157', precioMaquila:'104' },
                 { nombre: 'Lona 13 onzas alta resolución', descripcion: 'Menos de 1/4 hasta 1/8 M2 el costo es 100% extra (.25 a .125)',
                   precioPublico: '196', precioMaquila:'130' },
                 { nombre: 'Lona 13 onzas alta resolución', descripcion: 'Menos de 1/8 M2 el costo es 150% extra (-.125)',
                   precioPublico: '245', precioMaquila:'163' },
                 { nombre: 'Lona 13 onzas alta resolución', descripcion: 'Ojillo extra', precioPublico: '3',
                   precioMaquila: '3' },
                 { nombre: 'Vinil blanco impreso brillante alta resolución', descripcion: 'De 1 a 1/4 M2 (1m2 a .25)', precioPublico: '190',
                   precioMaquila: '150' },
                 { nombre: 'Vinil blanco impreso brillante alta resolución', descripcion: 'Menos de 1/4 hasta 1/8 (.25 a .125)',
                   precioPublico: '220', precioMaquila:'180' },
                 { nombre: 'Vinil blanco impreso brillante alta resolución', descripcion: 'Menos de 1/8 (.125 a -)', precioPublico: '250',
                   precioMaquila: '210' },
                 { nombre: 'Vinil blanco impreso mate alta resolución', descripcion: 'De 1 a 1/4 (1m2 a .25)', precioPublico: '260',
                   precioMaquila: '220' },
                 { nombre: 'Vinil blanco impreso mate alta resolución', descripcion: 'Menos de 1/4 hasta 1/8 (.25 a .125)', precioPublico: '290',
                   precioMaquila: '250' },
                 { nombre: 'Vinil blanco impreso mate alta resolución', descripcion: 'Menos de 1/8 (.125 a -)', precioPublico: '320',
                   precioMaquila: '280' },
                 { nombre: 'Vinil transparente impreso alta resolución', descripcion: 'De 1 a 1/4 (1m2 a .25)', precioPublico: '240',
                   precioMaquila: '210' },
                 { nombre: 'Vinil transparente impreso alta resolución', descripcion: 'Menos de 1/4 a 1/8 (.25 a .125)', precioPublico: '270',
                   precioMaquila: '240' },
                 { nombre: 'Vinil transparente impreso alta resolución', descripcion: 'Menos de 1/8 (.125 a -)', precioPublico: '300',
                   precioMaquila:'270' },
                 { nombre: 'Vinil estático blanco impreso alta resolución', descripcion: 'De 1 a 1/4 (1m2 a .25)', precioPublico: '250',
                   precioMaquila: '210' },
                 { nombre: 'Vinil estático blanco impreso alta resolución', descripcion: 'Menos de 1/4 a 1/8 (.25 a .125)', precioPublico: '280',
                  precioMaquila:'240' },
                 { nombre: 'Vinil estático blanco impreso alta resolución', descripcion: 'Menos de 1/8 (.125 a -)', precioPublico: '310',
                   precioMaquila:'270' },
                 { nombre: 'Vinil microperforado impreso alta resolución', descripcion: 'De 1 a 1/4 (1m2 a .25)', precioPublico: '280',
                   precioMaquila:'240' },
                 { nombre: 'Vinil microperforado impreso alta resolución', descripcion: 'Menos de 1/4 a 1/8 (.25 a .125)', precioPublico: '310',
                   precioMaquila:'270' },
                 { nombre: 'Vinil microperforado impreso alta resolución', descripcion: 'Menos de 1/8 (.125 a -)', precioPublico: '340',
                  precioMaquila:'300' },
                 { nombre: 'Sujado de vinil impreso', descripcion: 'De 1 a 1/4 M2 (1m2 a .25)',
                   precioPublico: '130', precioMaquila: '110' },
                 { nombre: 'Sujado de vinil impreso', descripcion: 'Menos de 1/4 hasta 1/8 M2 (.25 a .125)',
                   precioPublico: '180', precioMaquila: '160' },
                 { nombre: 'sujado de vinil impreso', descripcion: 'Corte manual',
                   precioPublico: '110', precioMaquila: '80' },
                 { nombre: 'Trovicel y coroplast', descripcion: 'Trovicel',
                   precioPublico: '590', precioMaquila: '470' },
                 { nombre: 'Trovicel y coroplast', descripcion: 'Coroplast',
                   precioPublico: '490', precioMaquila: '370' },
                 { nombre: 'Trovicel y coroplast', descripcion: 'Estireno cal. 40',
                   precioPublico: '390', precioMaquila: '320' },
                 { nombre: 'Trovicel y coroplast', descripcion: 'Iman',
                   precioPublico: '490', precioMaquila: '390' },
                 { nombre: 'Banderas publicitarias', descripcion: 'Grande, medida total .75 x 4.00, medida tela .75 x 3.00',
                   precioPublico: '1500', precioMaquila:'1100' },
                 { nombre: 'Banderas publicitarias', descripcion: 'Mediana, medida total 0.6 x 3.2, medida tela .0 x 2.40',
                   precioPublico: '1000', precioMaquila:'750' },
                 { nombre: 'Banderas publicitarias', descripcion: 'Chica. medida total 0.5 x 2.6, medida tela .50 x 2.00',
                   precioPublico: '700', precioMaquila: '525' },
                 { nombre: 'Banderas publicitarias', descripcion: 'Sólo tela, grande .75 x 3.00',
                   precioPublico: '1000', precioMaquila: '750' },
                 { nombre: 'Banderas publicitarias', descripcion: 'Sólo tela, mediana 0.6 x 2.40',
                   precioPublico: '700', precioMaquila: '525' },
                 { nombre: 'Banderas publicitarias', descripcion: 'Sólo tela, chica .50 x 2.00',
                   precioPublico: '500', precioMaquila: '400' },
                 { nombre: 'Bases para banderas', descripcion: 'Concreto', precioPublico: '60', precioMaquila: '45' },
                 { nombre: 'Bases para banderas', descripcion: 'Jardin', precioPublico: '70', precioMaquila: '55' },
                 { nombre: 'Bases para banderas', descripcion: 'Auto', precioPublico: '90', precioMaquila: '70' },
                 { nombre: 'Bases para banderas', descripcion: 'Plegable', precioPublico: '400', precioMaquila: '320' },
                 { nombre: 'Papel sublimado', descripcion: 'Tamaño carta', precioPublico: '16', precioMaquila: '12' },
                 { nombre: 'Papel sublimado', descripcion: 'Tamaño oficio', precioPublico: '20', precioMaquila: '15' },
                 { nombre: 'Papel sublimado', descripcion: 'Tamaño 2 carta', precioPublico: '24', precioMaquila: '18' },
                 { nombre: 'Papel sublimado', descripcion: 'Tamaño 13" x 20"', precioPublico: '34', precioMaquila: '25' },
                 { nombre: 'Papel sublimado', descripcion: 'Tamaño 13" x 40"', precioPublico: '52', precioMaquila: '40' },
                 { nombre: 'Papel sublimado y planchado', descripcion: 'Tamaño carta', precioPublico: '28', precioMaquila: '18' },
                 { nombre: 'Papel sublimado y planchado', descripcion: 'Tamaño oficio', precioPublico: '32', precioMaquila: '21' },
                 { nombre: 'Papel sublimado y planchado', descripcion: 'Tamaño 2 carta', precioPublico: '45', precioMaquila: '28' },
                 { nombre: 'Papel sublimado y planchado', descripcion: 'Tamaño 13" x 20"', precioPublico: '60', precioMaquila: '45' },
                 { nombre: 'Papel sublimado y planchado', descripcion: 'Tamaño 13" x 40"', precioPublico: '90', precioMaquila: '65' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 1', precioPublico: '50', precioMaquila: '40' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 2 a 5', precioPublico: '35', precioMaquila: '30' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 6 a 10', precioPublico: '30', precioMaquila: '25' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 11 a 25', precioPublico: '25', precioMaquila: '20' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 26 a 50', precioPublico: '22', precioMaquila: '18' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 51 a 100', precioPublico: '20', precioMaquila: '16' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'Frente 101 a 500', precioPublico: '18', precioMaquila: '15' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 1', precioPublico: '60', precioMaquila: '50' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 2 a 5', precioPublico: '45', precioMaquila: '35' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 6 a 10', precioPublico: '40', precioMaquila: '30' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 11 a 25', precioPublico: '35', precioMaquila: '25' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 26 a 50', precioPublico: '30', precioMaquila: '23' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 51 a 100', precioPublico: '27', precioMaquila: '21' },
                 { nombre: 'Credenciales PVC 8.5 x 5.4 CM', descripcion: 'F/v 101 a 500', precioPublico: '25', precioMaquila: '20' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta, pasta dura, ordinario 72 horas', precioPublico: '200', precioMaquila: '200', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta, pasta delgada, ordinario 72 horas', precioPublico: '110', precioMaquila: '110', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta, pasta dura, urgente 24 horas', precioPublico: '300', precioMaquila: '300', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta, pasta delgada, urgente 24 horas', precioPublico: '165', precioMaquila: '165', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta, pasta dura, extraurgente 4-6 horas', precioPublico: '400', precioMaquila: '400', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta, pasta delgada, extraurgente 4-6 horas', precioPublico: '220', precioMaquila: '220', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño oficio, pasta dura, ordinario 72 horas', precioPublico: '230', precioMaquila: '230', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño oficio, pasta delgada, ordinario 72 horas', precioPublico: '130', precioMaquila: '130', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño oficio, pasta dura, urgente 24 horas', precioPublico: '345', precioMaquila: '345', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño oficio, pasta delgada, urgente 24 horas', precioPublico: '195', precioMaquila: '195', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño oficio, pasta dura, extraurgente 4-6 horas', precioPublico: '460', precioMaquila: '460', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño oficio, pasta delgada, extraurgente 4-6 horas', precioPublico: '260', precioMaquila: '260', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño doble carta, pasta dura, ordinario 72 horas', precioPublico: '290', precioMaquila: '290', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño doble carta, pasta delgada, ordinario 72 horas', precioPublico: '160', precioMaquila: '160', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño doble carta, pasta dura, urgente 24 horas', precioPublico: '435', precioMaquila: '435', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño doble carta, pasta delgada, urgente 24 horas', precioPublico: '240', precioMaquila: '240', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño doble carta, pasta dura, extraurgente 4-6 horas', precioPublico: '580', precioMaquila: '580', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño doble carta, pasta delgada, extraurgente 4-6 horas', precioPublico: '320', precioMaquila: '320', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta digital, pasta dura, ordinario 72 horas', precioPublico: '270', precioMaquila: '270', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta digital, pasta delgada, ordinario 72 horas', precioPublico: '140', precioMaquila: '140', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta digital, pasta dura, urgente 24 horas', precioPublico: '405', precioMaquila: '405', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta digital, pasta delgada, urgente 24 horas', precioPublico: '210', precioMaquila: '210', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta digital, pasta dura, extraurgente 4-6 horas', precioPublico: '540', precioMaquila: '540', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño carta digital, pasta delgada, extraurgente 4-6 horas', precioPublico: '280', precioMaquila: '280', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño periodico, pasta dura, ordinario 72 horas', precioPublico: '500', precioMaquila: '500', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño periodico, pasta dura, urgente 24 horas', precioPublico: '750', precioMaquila: '750', descuentoMaquila: '15' },
                 { nombre: 'Encuadernación', descripcion: 'Tamaño periodico, pasta dura, extraurgente 4-6 horas', precioPublico: '1000', precioMaquila: '1000', descuentoMaquila: '15' }
                ])
User.create(email: 'admin@admin.com', token_auth: '123', tipos_usuarios_id: 1)
User.create(email: 'frodriguez13@ucol.mx', token_auth: 'Czee0I5GhMQ9M2anb5SF28YDM842', tipos_usuarios_id: 1)
User.create(email: 'bvadillo0@ucol.mx', token_auth: 'sUqtj2pW5Ef26uw9Q9px2IUcXuX2', tipos_usuarios_id: 1)
